### PR TITLE
macos fixes

### PR DESCRIPTION
**Pull request by nidegen**
these are the changes so that it compiles on mac. it should not interfere with linux, but maybe check first

also, i kinda prefer upper case commands in cmake:) do you agree on that?

### CODE REVIEW

**Comment by gocarlos** [comment]
@nidegen yes, lets agree on that :)

**Comment by nidegen** [comment]
oh, let me remove the example code and binaries first. sorry

**Comment by gocarlos** [comment]
I think we should clean the cmake a little bit, but this should be made in a separate PR :)

LGTM

**Comment by gocarlos** [comment]
Lgtm

**Pull request merged**
